### ISSUE TITLE
[Feature] Add navbar

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/json-generator#11]
Add a responsive navbar with invite vote and a discord tab to make it easy for users to get support!

**Comment by sunidhisachan** [comment]
@mezotv I want to try this . Please assign this to me.

**Comment by mezotv** [comment]
Hey sure!

**Comment by darshikaguptaa** [comment]
Hey I want to work on this.
Can you please assign it to me.

**Comment by mezotv** [comment]
Hey there is already someone asigned

**Comment by mezotv** [comment]
Hey, @sunidhisachan due to some recent changes I don't thing a navbar is necessary anymore. Im really sorry
