### ISSUE TITLE
A footer with your social media handles

### ISSUE THREAD

**Issue by InquisitiveMe15** [Would-You-Bot/json-generator#16]
Hey! I want to add a footer to your site containing your social media handle details. It will look good :)

**Comment by mezotv** [comment]
Sounds good sure!

**Comment by InquisitiveMe15** [comment]
Great! Thanks. Please assign this issue to me.

**Comment by forgetfulskybro** [comment]
> Great! Thanks. Please assign this issue to me.

Done! Thanks for contributing to this project. :)

**Comment by InquisitiveMe15** [comment]
Please label it hacktoberfest also
