### ISSUE TITLE
Adding feature of Light/Dark mode

### ISSUE THREAD

**Issue by theravi04** [Would-You-Bot/json-generator#17]
Adding feature of Light/Dark mode.
@mezotv kindly assign me this issue

**Comment by forgetfulskybro** [comment]
> Adding feature of Light/Dark mode. @mezotv kindly assign me this issue

Sorry to say but we've decided to not include an option for changing the background color.

**Comment by forgetfulskybro** [comment]
Accidentally closed. Thanks for contributing.
