### ISSUE TITLE
[Feature/Bug]

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/json-generator#21]
Add dark mode to local storage so it stays on page refresh.

Currently the dark mode toggle goes away after refreshing the page.

To fix this store the state in the local storage and make dark mode default.

**Comment by pixalquarks** [comment]
I would recommend using local storage, as cookies are better when we need to send information to the server.

**Comment by mezotv** [comment]
Local storage would also work yea.

**Comment by pixalquarks** [comment]
Please assign this issue to me.

**Comment by mezotv** [comment]
> Please assign this issue to me.

Done! Thanks for contributing!
