### ISSUE TITLE
Write README.md file with socalify element and contributors too

### ISSUE THREAD

**Issue by Mitternachtsmond** [Would-You-Bot/json-generator#24]
- Glimpse
<img width="473" alt="image" src="https://user-images.githubusercontent.com/85838936/193840231-422d3c99-3f10-40da-8dc4-c593e12f07fe.png">

- Automatically adding contributors to README.md

**Comment by mezotv** [comment]
Looks good. Would you be available to work on this?

**Comment by Mitternachtsmond** [comment]
Yes I would like to work on this

**Comment by Mitternachtsmond** [comment]
Can you assign it to me @mezotv

**Comment by mezotv** [comment]
Sounds good ill assign both issues to you!

**Comment by mezotv** [comment]
Hows it going so far @Mitternachtsmond?

**Comment by Mitternachtsmond** [comment]
Almost done @mezotv

**Comment by mezotv** [comment]
> Almost done @mezotv

Epic!
