### ISSUE TITLE
[Mobile Bug] Responsive design

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/json-generator#37]
The responsive design on mobile looks a bit weird. ![Screenshot_20221006-231121_Chrome.jpg](https://user-images.githubusercontent.com/68947960/194419509-932e74b0-e1c7-4db2-a520-badcb096a693.jpg)

**Comment by Maaz4324** [comment]
please assign this to me

**Comment by forgetfulskybro** [comment]
Some other contributors fixed this issue when their PR was accepted. Don't believe we need this issue anymore. Thanks for participating, Maaz!

![image](https://user-images.githubusercontent.com/47897305/194430480-ecb3c9f8-0616-42f0-b986-62e0afada456.png)
