### ISSUE TITLE
[Issue] Responsive site

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/json-generator#9]
Site isn't really responsive on mobile should fix soon!

**Comment by HammadKhaan** [comment]
@mezotv assign it to me.

**Comment by mezotv** [comment]
Sure!

**Comment by theravi04** [comment]
Sir I would like to fix this issue for hacktoberfest 2022.

**Comment by mezotv** [comment]
You can try but there is already someone working on it

**Comment by theravi04** [comment]
Ok Sir
